### ISSUE TITLE
Install texlive so that "download as pdf works"

### ISSUE THREAD

**Issue by moorepants** [ixjlyons/jupyterhub-deploy-teaching#11]
Can you get the pdf download working? Should just be some texlive apt get installs.

**Comment by moorepants** [comment]
I'm just doing it. Sorry to bug ya.

**Comment by moorepants** [comment]
I did this:

agt-get install aptitude pandoc texlive-full

**Comment by moorepants** [comment]
ok, this seems to work now

**Comment by ixjlyons** [comment]
Note this issue: https://github.com/jupyter/nbconvert/issues/552

**Comment by moorepants** [comment]
I hit that already with one of my cw notebooks, but then tried a simple notebook with a markdown figure and it worked, even in sub dirs. Not sure what the difference was.

**Comment by ptorru** [comment]
Hello there, I don't know if this is helpful but, I am running debian Jessie, I am facing the same problem.

I just installed texlive-full : 
`Setting up texlive-full (2014.20141024-2+deb8u1) ...`

But this has not fixed the issue. 

I am using:

```
The version of the notebook server is 4.3.1 and is running on:
Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

Any suggestions?

**Comment by moorepants** [comment]
As a work around you can use nbconvert to convert to latex and manually compile the file into a PDF. The images will be found if you do that.

**Comment by ptorru** [comment]
@moorepants Thanks so much for the suggestion.

I still had to replace the absolute paths on the `\includegraphics` lines with relative ones, however it did allow me to get the pictures on the final PDF.

Again many thanks indeed!
