### ISSUE TITLE
move repo to mechmotum

### ISSUE THREAD

**Issue by moorepants** [ixjlyons/jupyterhub-deploy-teaching#19]
Kenny would you be wiling to move this fork to the mechmotum user?

**Comment by ixjlyons** [comment]
Of course, figured you'd want to transfer it somewhere eventually.

**Comment by ixjlyons** [comment]
Seems like I have to have the ability to create repositories in your organization (I think adding you as a collaborator to this repo wouldn't be enough): https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by moorepants** [comment]
i can add you to the group, will do tomorrow

**Comment by moorepants** [comment]
Kenny, just sent you an invite to the mechmotum group. Can you move this repo over? I've got students working on this now and they will likely do some contributions.

**Comment by moorepants** [comment]
Thanks!
