### ISSUE TITLE
Installed nbextensions

### ISSUE THREAD

**Issue by moorepants** [ixjlyons/jupyterhub-deploy-teaching#9]
I did this on the server:

```
conda install jupyter_contrib_nbextensions
jupyter nbextension enable exercise2/main
jupyter nbextension enable rubberband/main
```

**Comment by ixjlyons** [comment]
Added. Using `jupyter nbextension enable exercise2/main --system --sys-prefix` also seems to enable it for all users by default now. Also, it looks like it can be used without rubberband (shift+click to select multiple cells), which was causing annoying issues.
